# Generated by Django 4.0.2 on 2022-05-23 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('source_dest', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('arrival_time', models.TimeField()),
                ('depart_time', models.TimeField()),
                ('no_passengers', models.IntegerField()),
            ],
        ),
    ]
