# Generated by Django 4.0.2 on 2022-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_class_left', models.IntegerField(blank=True, null=True)),
                ('economy_left', models.IntegerField(blank=True, null=True)),
                ('coach_left', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'flight',
                'managed': False,
            },
        ),
    ]
